# Basic
title: Gukong's Blog
#subtitle: iOS development experience && learning experience for new knowledge
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: iOS developer
creator: <a href="https://github.com/gukong">@gukong</a>

#url: "https://github.com/onevcat/vno-jekyll"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/gukong'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: vno-jekyll
    duoshuo: gukong123
    
# Social
social:
    #weibo: onevcat
    github: gukong
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: 1239242238@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
